name = "DiscreteGeneralizedSensitivities"
uuid = "eb9eecac-26dc-45b7-83f2-1d878d2a5a88"
version = "1.0.0-DEV"
authors = ["Sasha Fleming <fleming@stce.rwth-aachen.de> and contributors"]

[deps]
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
SimpleIntegration = "f1de6737-2331-4f40-83c2-33cf2af9fc78"

[compat]
DifferentiationInterface = "0.7.13"
ForwardDiff = "1.3.0"
Interpolations = "0.16.2"
SimpleIntegration = "0.1.3"
julia = "1.11"
