name = "DiscreteGeneralizedSensitivities"
uuid = "eb9eecac-26dc-45b7-83f2-1d878d2a5a88"
version = "0.1.1"
authors = ["Sasha Fleming <fleming@stce.rwth-aachen.de> and contributors"]

[deps]
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
SimpleIntegration = "f1de6737-2331-4f40-83c2-33cf2af9fc78"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
DifferentiationInterface = "0.7.13"
ForwardDiff = "1.3.0"
LoopVectorization = "0.12.173"
SimpleIntegration = "0.1.3"
StaticArrays = "1.9.16"
Tullio = "0.3.8"
julia = "1.11"
